[package]
name = "sega-bass-fishing-2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
poise = "0.6.1"
serde = "1.0.210"
serde_derive = "1.0.210"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
toml = "0.8.19"
